/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CursosIndexRouteImport } from './routes/cursos.index'
import { Route as CursosSlugRouteImport } from './routes/cursos.$slug'
import { Route as CertificadoValidarCodigoRouteImport } from './routes/certificado.validar.$codigo'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosIndexRoute = CursosIndexRouteImport.update({
  id: '/cursos/',
  path: '/cursos/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosSlugRoute = CursosSlugRouteImport.update({
  id: '/cursos/$slug',
  path: '/cursos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificadoValidarCodigoRoute =
  CertificadoValidarCodigoRouteImport.update({
    id: '/certificado/validar/$codigo',
    path: '/certificado/validar/$codigo',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/sobre': typeof SobreRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/cursos/': typeof CursosIndexRoute
  '/certificado/validar/$codigo': typeof CertificadoValidarCodigoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/sobre': typeof SobreRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/cursos': typeof CursosIndexRoute
  '/certificado/validar/$codigo': typeof CertificadoValidarCodigoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/sobre': typeof SobreRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/cursos/': typeof CursosIndexRoute
  '/certificado/validar/$codigo': typeof CertificadoValidarCodigoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contato'
    | '/sobre'
    | '/cursos/$slug'
    | '/cursos/'
    | '/certificado/validar/$codigo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contato'
    | '/sobre'
    | '/cursos/$slug'
    | '/cursos'
    | '/certificado/validar/$codigo'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/contato'
    | '/sobre'
    | '/cursos/$slug'
    | '/cursos/'
    | '/certificado/validar/$codigo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ContatoRoute: typeof ContatoRoute
  SobreRoute: typeof SobreRoute
  CursosSlugRoute: typeof CursosSlugRoute
  CursosIndexRoute: typeof CursosIndexRoute
  CertificadoValidarCodigoRoute: typeof CertificadoValidarCodigoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/': {
      id: '/cursos/'
      path: '/cursos'
      fullPath: '/cursos/'
      preLoaderRoute: typeof CursosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$slug': {
      id: '/cursos/$slug'
      path: '/cursos/$slug'
      fullPath: '/cursos/$slug'
      preLoaderRoute: typeof CursosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificado/validar/$codigo': {
      id: '/certificado/validar/$codigo'
      path: '/certificado/validar/$codigo'
      fullPath: '/certificado/validar/$codigo'
      preLoaderRoute: typeof CertificadoValidarCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ContatoRoute: ContatoRoute,
  SobreRoute: SobreRoute,
  CursosSlugRoute: CursosSlugRoute,
  CursosIndexRoute: CursosIndexRoute,
  CertificadoValidarCodigoRoute: CertificadoValidarCodigoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
