/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CursosIndexRouteImport } from './routes/cursos.index'
import { Route as CursosSlugRouteImport } from './routes/cursos.$slug'
import { Route as AuthenticatedAlunoRouteImport } from './routes/_authenticated/aluno'
import { Route as CertificadoValidarIndexRouteImport } from './routes/certificado.validar.index'
import { Route as AuthenticatedAlunoIndexRouteImport } from './routes/_authenticated/aluno.index'
import { Route as CertificadoValidarCodigoRouteImport } from './routes/certificado.validar.$codigo'
import { Route as AuthenticatedAlunoMeusCursosRouteImport } from './routes/_authenticated/aluno.meus-cursos'
import { Route as AuthenticatedAlunoCursosDisponiveisRouteImport } from './routes/_authenticated/aluno.cursos-disponiveis'
import { Route as AuthenticatedAlunoCertificadosRouteImport } from './routes/_authenticated/aluno.certificados'
import { Route as AuthenticatedAlunoCarteirinhaRouteImport } from './routes/_authenticated/aluno.carteirinha'
import { Route as AuthenticatedAlunoCursoIdRouteImport } from './routes/_authenticated/aluno.curso.$id'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosIndexRoute = CursosIndexRouteImport.update({
  id: '/cursos/',
  path: '/cursos/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosSlugRoute = CursosSlugRouteImport.update({
  id: '/cursos/$slug',
  path: '/cursos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAlunoRoute = AuthenticatedAlunoRouteImport.update({
  id: '/aluno',
  path: '/aluno',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CertificadoValidarIndexRoute = CertificadoValidarIndexRouteImport.update({
  id: '/certificado/validar/',
  path: '/certificado/validar/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAlunoIndexRoute = AuthenticatedAlunoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAlunoRoute,
} as any)
const CertificadoValidarCodigoRoute =
  CertificadoValidarCodigoRouteImport.update({
    id: '/certificado/validar/$codigo',
    path: '/certificado/validar/$codigo',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAlunoMeusCursosRoute =
  AuthenticatedAlunoMeusCursosRouteImport.update({
    id: '/meus-cursos',
    path: '/meus-cursos',
    getParentRoute: () => AuthenticatedAlunoRoute,
  } as any)
const AuthenticatedAlunoCursosDisponiveisRoute =
  AuthenticatedAlunoCursosDisponiveisRouteImport.update({
    id: '/cursos-disponiveis',
    path: '/cursos-disponiveis',
    getParentRoute: () => AuthenticatedAlunoRoute,
  } as any)
const AuthenticatedAlunoCertificadosRoute =
  AuthenticatedAlunoCertificadosRouteImport.update({
    id: '/certificados',
    path: '/certificados',
    getParentRoute: () => AuthenticatedAlunoRoute,
  } as any)
const AuthenticatedAlunoCarteirinhaRoute =
  AuthenticatedAlunoCarteirinhaRouteImport.update({
    id: '/carteirinha',
    path: '/carteirinha',
    getParentRoute: () => AuthenticatedAlunoRoute,
  } as any)
const AuthenticatedAlunoCursoIdRoute =
  AuthenticatedAlunoCursoIdRouteImport.update({
    id: '/curso/$id',
    path: '/curso/$id',
    getParentRoute: () => AuthenticatedAlunoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/sobre': typeof SobreRoute
  '/aluno': typeof AuthenticatedAlunoRouteWithChildren
  '/cursos/$slug': typeof CursosSlugRoute
  '/cursos/': typeof CursosIndexRoute
  '/aluno/carteirinha': typeof AuthenticatedAlunoCarteirinhaRoute
  '/aluno/certificados': typeof AuthenticatedAlunoCertificadosRoute
  '/aluno/cursos-disponiveis': typeof AuthenticatedAlunoCursosDisponiveisRoute
  '/aluno/meus-cursos': typeof AuthenticatedAlunoMeusCursosRoute
  '/certificado/validar/$codigo': typeof CertificadoValidarCodigoRoute
  '/aluno/': typeof AuthenticatedAlunoIndexRoute
  '/certificado/validar/': typeof CertificadoValidarIndexRoute
  '/aluno/curso/$id': typeof AuthenticatedAlunoCursoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/sobre': typeof SobreRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/cursos': typeof CursosIndexRoute
  '/aluno/carteirinha': typeof AuthenticatedAlunoCarteirinhaRoute
  '/aluno/certificados': typeof AuthenticatedAlunoCertificadosRoute
  '/aluno/cursos-disponiveis': typeof AuthenticatedAlunoCursosDisponiveisRoute
  '/aluno/meus-cursos': typeof AuthenticatedAlunoMeusCursosRoute
  '/certificado/validar/$codigo': typeof CertificadoValidarCodigoRoute
  '/aluno': typeof AuthenticatedAlunoIndexRoute
  '/certificado/validar': typeof CertificadoValidarIndexRoute
  '/aluno/curso/$id': typeof AuthenticatedAlunoCursoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/sobre': typeof SobreRoute
  '/_authenticated/aluno': typeof AuthenticatedAlunoRouteWithChildren
  '/cursos/$slug': typeof CursosSlugRoute
  '/cursos/': typeof CursosIndexRoute
  '/_authenticated/aluno/carteirinha': typeof AuthenticatedAlunoCarteirinhaRoute
  '/_authenticated/aluno/certificados': typeof AuthenticatedAlunoCertificadosRoute
  '/_authenticated/aluno/cursos-disponiveis': typeof AuthenticatedAlunoCursosDisponiveisRoute
  '/_authenticated/aluno/meus-cursos': typeof AuthenticatedAlunoMeusCursosRoute
  '/certificado/validar/$codigo': typeof CertificadoValidarCodigoRoute
  '/_authenticated/aluno/': typeof AuthenticatedAlunoIndexRoute
  '/certificado/validar/': typeof CertificadoValidarIndexRoute
  '/_authenticated/aluno/curso/$id': typeof AuthenticatedAlunoCursoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contato'
    | '/sobre'
    | '/aluno'
    | '/cursos/$slug'
    | '/cursos/'
    | '/aluno/carteirinha'
    | '/aluno/certificados'
    | '/aluno/cursos-disponiveis'
    | '/aluno/meus-cursos'
    | '/certificado/validar/$codigo'
    | '/aluno/'
    | '/certificado/validar/'
    | '/aluno/curso/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contato'
    | '/sobre'
    | '/cursos/$slug'
    | '/cursos'
    | '/aluno/carteirinha'
    | '/aluno/certificados'
    | '/aluno/cursos-disponiveis'
    | '/aluno/meus-cursos'
    | '/certificado/validar/$codigo'
    | '/aluno'
    | '/certificado/validar'
    | '/aluno/curso/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contato'
    | '/sobre'
    | '/_authenticated/aluno'
    | '/cursos/$slug'
    | '/cursos/'
    | '/_authenticated/aluno/carteirinha'
    | '/_authenticated/aluno/certificados'
    | '/_authenticated/aluno/cursos-disponiveis'
    | '/_authenticated/aluno/meus-cursos'
    | '/certificado/validar/$codigo'
    | '/_authenticated/aluno/'
    | '/certificado/validar/'
    | '/_authenticated/aluno/curso/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContatoRoute: typeof ContatoRoute
  SobreRoute: typeof SobreRoute
  CursosSlugRoute: typeof CursosSlugRoute
  CursosIndexRoute: typeof CursosIndexRoute
  CertificadoValidarCodigoRoute: typeof CertificadoValidarCodigoRoute
  CertificadoValidarIndexRoute: typeof CertificadoValidarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/': {
      id: '/cursos/'
      path: '/cursos'
      fullPath: '/cursos/'
      preLoaderRoute: typeof CursosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$slug': {
      id: '/cursos/$slug'
      path: '/cursos/$slug'
      fullPath: '/cursos/$slug'
      preLoaderRoute: typeof CursosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/aluno': {
      id: '/_authenticated/aluno'
      path: '/aluno'
      fullPath: '/aluno'
      preLoaderRoute: typeof AuthenticatedAlunoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/certificado/validar/': {
      id: '/certificado/validar/'
      path: '/certificado/validar'
      fullPath: '/certificado/validar/'
      preLoaderRoute: typeof CertificadoValidarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/aluno/': {
      id: '/_authenticated/aluno/'
      path: '/'
      fullPath: '/aluno/'
      preLoaderRoute: typeof AuthenticatedAlunoIndexRouteImport
      parentRoute: typeof AuthenticatedAlunoRoute
    }
    '/certificado/validar/$codigo': {
      id: '/certificado/validar/$codigo'
      path: '/certificado/validar/$codigo'
      fullPath: '/certificado/validar/$codigo'
      preLoaderRoute: typeof CertificadoValidarCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/aluno/meus-cursos': {
      id: '/_authenticated/aluno/meus-cursos'
      path: '/meus-cursos'
      fullPath: '/aluno/meus-cursos'
      preLoaderRoute: typeof AuthenticatedAlunoMeusCursosRouteImport
      parentRoute: typeof AuthenticatedAlunoRoute
    }
    '/_authenticated/aluno/cursos-disponiveis': {
      id: '/_authenticated/aluno/cursos-disponiveis'
      path: '/cursos-disponiveis'
      fullPath: '/aluno/cursos-disponiveis'
      preLoaderRoute: typeof AuthenticatedAlunoCursosDisponiveisRouteImport
      parentRoute: typeof AuthenticatedAlunoRoute
    }
    '/_authenticated/aluno/certificados': {
      id: '/_authenticated/aluno/certificados'
      path: '/certificados'
      fullPath: '/aluno/certificados'
      preLoaderRoute: typeof AuthenticatedAlunoCertificadosRouteImport
      parentRoute: typeof AuthenticatedAlunoRoute
    }
    '/_authenticated/aluno/carteirinha': {
      id: '/_authenticated/aluno/carteirinha'
      path: '/carteirinha'
      fullPath: '/aluno/carteirinha'
      preLoaderRoute: typeof AuthenticatedAlunoCarteirinhaRouteImport
      parentRoute: typeof AuthenticatedAlunoRoute
    }
    '/_authenticated/aluno/curso/$id': {
      id: '/_authenticated/aluno/curso/$id'
      path: '/curso/$id'
      fullPath: '/aluno/curso/$id'
      preLoaderRoute: typeof AuthenticatedAlunoCursoIdRouteImport
      parentRoute: typeof AuthenticatedAlunoRoute
    }
  }
}

interface AuthenticatedAlunoRouteChildren {
  AuthenticatedAlunoCarteirinhaRoute: typeof AuthenticatedAlunoCarteirinhaRoute
  AuthenticatedAlunoCertificadosRoute: typeof AuthenticatedAlunoCertificadosRoute
  AuthenticatedAlunoCursosDisponiveisRoute: typeof AuthenticatedAlunoCursosDisponiveisRoute
  AuthenticatedAlunoMeusCursosRoute: typeof AuthenticatedAlunoMeusCursosRoute
  AuthenticatedAlunoIndexRoute: typeof AuthenticatedAlunoIndexRoute
  AuthenticatedAlunoCursoIdRoute: typeof AuthenticatedAlunoCursoIdRoute
}

const AuthenticatedAlunoRouteChildren: AuthenticatedAlunoRouteChildren = {
  AuthenticatedAlunoCarteirinhaRoute: AuthenticatedAlunoCarteirinhaRoute,
  AuthenticatedAlunoCertificadosRoute: AuthenticatedAlunoCertificadosRoute,
  AuthenticatedAlunoCursosDisponiveisRoute:
    AuthenticatedAlunoCursosDisponiveisRoute,
  AuthenticatedAlunoMeusCursosRoute: AuthenticatedAlunoMeusCursosRoute,
  AuthenticatedAlunoIndexRoute: AuthenticatedAlunoIndexRoute,
  AuthenticatedAlunoCursoIdRoute: AuthenticatedAlunoCursoIdRoute,
}

const AuthenticatedAlunoRouteWithChildren =
  AuthenticatedAlunoRoute._addFileChildren(AuthenticatedAlunoRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlunoRoute: typeof AuthenticatedAlunoRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlunoRoute: AuthenticatedAlunoRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContatoRoute: ContatoRoute,
  SobreRoute: SobreRoute,
  CursosSlugRoute: CursosSlugRoute,
  CursosIndexRoute: CursosIndexRoute,
  CertificadoValidarCodigoRoute: CertificadoValidarCodigoRoute,
  CertificadoValidarIndexRoute: CertificadoValidarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
